from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DATA_YAML = ROOT / "datasets" / "data.yaml"
EXTERNAL_FRAMES_DIR = ROOT / "video-frame" / "frames"
EXTERNAL_LABELS_DIR = ROOT / "video-frame" / "output"

OUTPUTS_DIR = ROOT / "outputs"
RUNS_DIR = OUTPUTS_DIR / "runs"
BEST_MODEL_FILE = OUTPUTS_DIR / "best_model.txt"
EXTERNAL_DIR = OUTPUTS_DIR / "external"
NO_HYBRID_DIR = EXTERNAL_DIR / "no_hybrid"
HYBRID_DIR = EXTERNAL_DIR / "hybrid"

REPORTS_DIR = ROOT / "reports"
PLOTS_DIR = REPORTS_DIR / "plots"

SEED = 42

EPOCHS = 200
IMGSZ = 640
BATCH = 16
CONF_THRES = 0.278
IOU_THRES = 0.5
PATIENCE = 30

TRAIN_MODELS = [
    ("yolov5s", "yolov5su.pt"),
    ("yolov8s", "yolov8s.pt"),
    ("yolo26s", "yolo26s.pt"),
]

# Fixed ROI parameters from user-provided notebook code.
ROI_TOP_Y_RATIO = 0.45
ROI_TOP_LEFT_X_RATIO = 0.45
ROI_TOP_RIGHT_X_RATIO = 0.55
# Hex ROI (top trapezoid + bottom rectangle).
ROI_MID_Y_RATIO = 0.6
ROI_BOTTOM_Y_RATIO = 0.9
ROI_BOTTOM_LEFT_X_RATIO = 0.0
ROI_BOTTOM_RIGHT_X_RATIO = 1.0
ROI_DILATE_PX = 50
INNER_ERODE_PX = 40
BG_VALUE = 114

MIN_AREA_RATIO = 0.00025
MAX_AREA_RATIO = 0.05
MIN_ASPECT = 0.30
MAX_ASPECT = 3.50

# Dynamic horizon ROI parameters.
HORIZON_ENABLE = False
HORIZON_RESIZE_W = 960
HORIZON_MAX_SLOPE_DEG = 12.0
HORIZON_MAX_Y_RATIO = 0.62
HORIZON_MIN_LINE_LEN_RATIO = 0.12
HORIZON_EMA_ALPHA = 0.30
HORIZON_MAX_STEP_RATIO = 0.015
HORIZON_TOP_MARGIN_RATIO = 0.00
HORIZON_MIN_CONF = 0.35
HORIZON_MAX_MISS = 12
HORIZON_TOP_MIN_RATIO = 0.40
HORIZON_TOP_MAX_RATIO = 0.55
HORIZON_MEDIAN_WIN = 7
HORIZON_UPDATE_INTERVAL = 5
HORIZON_GATE_MIN_DELTA_RATIO = 0.004
HORIZON_GATE_MAX_DELTA_RATIO = 0.08
